/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "pbmessage.pb-c.h"
void   pb_message__init
                     (PbMessage         *message)
{
  static PbMessage init_value = PB_MESSAGE__INIT;
  *message = init_value;
}
size_t pb_message__get_packed_size
                     (const PbMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pb_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb_message__pack
                     (const PbMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pb_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb_message__pack_to_buffer
                     (const PbMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pb_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbMessage *
       pb_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbMessage *)
     protobuf_c_message_unpack (&pb_message__descriptor,
                                allocator, len, data);
}
void   pb_message__free_unpacked
                     (PbMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pb_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pb_message__field_descriptors[2] =
{
  {
    "T",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PbMessage, t),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PbMessage, message),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb_message__field_indices_by_name[] = {
  0,   /* field[0] = T */
  1,   /* field[1] = message */
};
static const ProtobufCIntRange pb_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pb_message__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "pbMessage",
  "PbMessage",
  "PbMessage",
  "",
  sizeof(PbMessage),
  2,
  pb_message__field_descriptors,
  pb_message__field_indices_by_name,
  1,  pb_message__number_ranges,
  (ProtobufCMessageInit) pb_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
