/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_pbmessage_2eproto__INCLUDED
#define PROTOBUF_C_pbmessage_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _PbMessage PbMessage;


/* --- enums --- */


/* --- messages --- */

struct  _PbMessage
{
  ProtobufCMessage base;
  int32_t t;
  ProtobufCBinaryData message;
};
#define PB_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pb_message__descriptor) \
    , 0, {0,NULL} }


/* PbMessage methods */
void   pb_message__init
                     (PbMessage         *message);
size_t pb_message__get_packed_size
                     (const PbMessage   *message);
size_t pb_message__pack
                     (const PbMessage   *message,
                      uint8_t             *out);
size_t pb_message__pack_to_buffer
                     (const PbMessage   *message,
                      ProtobufCBuffer     *buffer);
PbMessage *
       pb_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pb_message__free_unpacked
                     (PbMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PbMessage_Closure)
                 (const PbMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pb_message__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_pbmessage_2eproto__INCLUDED */
